import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { AiSummarizer } from "../services/openai";
import { runDailyChangelogCron } from "../cron/daily-runner";
import { InMemoryStore } from "../store/memory";

const summarizer: AiSummarizer = {
  summarize: async (pullRequests) => ({
    title: pullRequests.map((pr) => `PR ${pr.number}`).join(", "),
    summary: "Customer-facing updates were generated by the scheduler.",
    category: "improvement",
    confidence: 0.95,
    sensitive: false,
  }),
};

describe("daily changelog cron", () => {
  test("processes due changelogs and closes its store", async () => {
    const store = InMemoryStore.seeded();
    let closed = false;
    store.close = async () => {
      closed = true;
    };
    store.pullRequests.push({
      id: "pr_50",
      number: 50,
      title: "Improve dashboard loading",
      body: "Dashboard data now loads in fewer round trips.",
      labels: ["improvement"],
      mergedAt: "2026-06-06T04:15:00.000Z",
      url: "https://github.com/acme/app/pull/50",
      repository: "acme/app",
      author: "mona",
    });

    const result = await runDailyChangelogCron({
      now: new Date("2026-06-07T00:30:00.000Z"),
      store,
      summarizer,
    });

    expect(result.processed).toBe(1);
    expect(
      store.changelogs.find((changelog) => changelog.id === "cl_acme")
        ?.lastGeneratedWindowEnd,
    ).toBe("2026-06-06T23:00:00.000Z");
    expect(store.entries.some((entry) => entry.title === "PR 50")).toBe(true);
    expect(closed).toBe(true);
  });

  test("does not fail when a due window was already generated", async () => {
    const store = InMemoryStore.seeded();
    const now = new Date("2026-06-07T00:30:00.000Z");

    await runDailyChangelogCron({ now, store, summarizer });
    store.changelogs[0]!.lastGeneratedWindowEnd = null;

    await expect(
      runDailyChangelogCron({ now, store, summarizer }),
    ).resolves.toEqual({ processed: 1 });
  });

  test("keeps running when a due changelog is blocked by AI credits", async () => {
    const store = InMemoryStore.seeded();
    store.workspaces[0]!.billingMode = "hosted";
    store.complimentaryAccessGrants.push({
      id: "grant_exhausted",
      workspaceId: "ws_acme",
      planId: "watermelon",
      reason: "Test grant",
      grantedBy: "operator@example.com",
      expiresAt: null,
      createdAt: new Date().toISOString(),
    });
    const now = new Date("2026-06-07T00:30:00.000Z");
    store.aiUsageEvents.push({
      id: "usage_exhausted",
      workspaceId: "ws_acme",
      stripeCustomerId: null,
      sourceId: "generation:cl_acme:month",
      inputTokens: 1_000_000,
      cachedInputTokens: 0,
      outputTokens: 0,
      totalTokens: 1_000_000,
      rechargePacksReported: 0,
      createdAt: new Date().toISOString(),
      reportedAt: null,
    });
    store.pullRequests.push({
      id: "pr_credits_blocked",
      number: 55,
      title: "Add customer export controls",
      body: "Customers can choose which fields to export.",
      labels: ["feature"],
      mergedAt: "2026-06-06T04:30:00.000Z",
      url: "https://github.com/acme/app/pull/55",
      repository: "acme/app",
      author: "mona",
    });
    store.workspaces.push({
      ...store.workspaces[0]!,
      id: "ws_healthy",
      name: "Healthy workspace",
      billingMode: "self-hosted",
    });
    store.repositories.push({
      ...store.repositories[0]!,
      id: "repo_healthy",
      workspaceId: "ws_healthy",
      owner: "healthy",
      name: "app",
      fullName: "healthy/app",
    });
    store.changelogs.push({
      ...store.changelogs[0]!,
      id: "cl_healthy",
      workspaceId: "ws_healthy",
      repositoryId: "repo_healthy",
      slug: "healthy-app",
      name: "Healthy App",
      repository: "healthy/app",
      settings: { ...store.changelogs[0]!.settings },
    });
    store.pullRequests.push({
      id: "pr_healthy",
      number: 56,
      title: "Improve customer search",
      body: "Customers can find saved records more quickly.",
      labels: ["improvement"],
      mergedAt: "2026-06-06T05:30:00.000Z",
      url: "https://github.com/healthy/app/pull/56",
      repository: "healthy/app",
      author: "mona",
    });
    const warnings: Array<{ message: string; details: unknown }> = [];

    await expect(
      runDailyChangelogCron({
        now,
        store,
        summarizer,
        logger: {
          warn(message, details) {
            warnings.push({ message, details });
          },
        },
      }),
    ).resolves.toEqual({ processed: 1 });

    expect(warnings).toEqual([
      {
        message: "Skipped entitlement-blocked changelog generation.",
        details: {
          changelogId: "cl_acme",
          reason:
            "The complimentary AI credit allowance is used. It resets next month.",
          status: 402,
        },
      },
    ]);
    expect(store.changelogs[0]!.lastGeneratedWindowEnd).toBeNull();
    expect(store.changelogs[1]!.lastGeneratedWindowEnd).toBe(
      "2026-06-06T23:00:00.000Z",
    );
    expect(store.entries.some((entry) => entry.title === "PR 56")).toBe(true);
  });

  test("processes a queued merge generation job", async () => {
    const store = InMemoryStore.seeded();
    store.changelogs[0].settings.scheduleFrequency = "on-merge";
    store.pullRequests.push({
      id: "pr_51",
      number: 51,
      title: "Add export controls",
      body: "Customers can now choose which fields to export.",
      labels: ["feature"],
      mergedAt: "2026-06-06T04:30:00.000Z",
      url: "https://github.com/acme/app/pull/51",
      repository: "acme/app",
      author: "mona",
    });
    await store.enqueueMergeGenerationJob({
      changelogId: "cl_acme",
      pullRequestNumber: 51,
      windowStartedAt: "2026-06-06T04:30:00.000Z",
      windowEndedAt: "2026-06-06T04:30:00.051Z",
    });

    const result = await runDailyChangelogCron({
      now: new Date("2026-06-06T04:31:00.000Z"),
      store,
      summarizer,
    });

    expect(result.processed).toBe(1);
    expect(store.mergeGenerationJobs[0]?.status).toBe("completed");
    expect(
      store.entries.some((entry) =>
        entry.sourcePullRequests.some(
          (pullRequest) => pullRequest.number === 51,
        ),
      ),
    ).toBe(true);
  });

  test("only processes release-mode changelogs when a release job is queued", async () => {
    const store = InMemoryStore.seeded();
    store.changelogs[0]!.settings.generationSource = "releases";
    store.pullRequests.push({
      id: "pr_54",
      number: 54,
      title: "Add release dashboard",
      body: "Customers can now review release activity.",
      labels: ["feature"],
      mergedAt: "2026-06-06T04:30:00.000Z",
      url: "https://github.com/acme/app/pull/54",
      repository: "acme/app",
      author: "mona",
    });

    expect(
      await runDailyChangelogCron({
        now: new Date("2026-06-07T00:30:00.000Z"),
        store,
        summarizer,
      }),
    ).toEqual({ processed: 0 });

    await store.enqueueReleaseGenerationJob({
      changelogId: "cl_acme",
      tagName: "v3.0.0",
      windowStartedAt: "2026-06-01T00:00:00.000Z",
      windowEndedAt: "2026-06-07T02:00:00.000Z",
    });
    expect(
      await runDailyChangelogCron({
        now: new Date("2026-06-07T02:01:00.000Z"),
        store,
        summarizer,
      }),
    ).toEqual({ processed: 1 });
    expect(store.mergeGenerationJobs[0]?.status).toBe("completed");
    expect(
      store.entries.some((entry) =>
        entry.sourcePullRequests.some(
          (pullRequest) => pullRequest.number === 54,
        ),
      ),
    ).toBe(true);
  });

  test("retries a queued merge generation job after a transient failure", async () => {
    const store = InMemoryStore.seeded();
    store.changelogs[0].settings.scheduleFrequency = "on-merge";
    store.pullRequests.push({
      id: "pr_52",
      number: 52,
      title: "Improve import feedback",
      body: "Customers now see actionable import errors.",
      labels: ["improvement"],
      mergedAt: "2026-06-06T04:45:00.000Z",
      url: "https://github.com/acme/app/pull/52",
      repository: "acme/app",
      author: "mona",
    });
    await store.enqueueMergeGenerationJob({
      changelogId: "cl_acme",
      pullRequestNumber: 52,
      windowStartedAt: "2026-06-06T04:45:00.000Z",
      windowEndedAt: "2026-06-06T04:45:00.052Z",
    });
    let calls = 0;
    const flakySummarizer: AiSummarizer = {
      summarize: async (pullRequests) => {
        calls += 1;
        if (calls === 1) throw new Error("temporary AI outage");
        return summarizer.summarize(pullRequests);
      },
    };

    await runDailyChangelogCron({
      now: new Date("2026-06-06T04:46:00.000Z"),
      store,
      summarizer: flakySummarizer,
    });
    expect(store.mergeGenerationJobs[0]).toMatchObject({
      status: "pending",
      attemptCount: 1,
      lastError: "temporary AI outage",
      nextAttemptAt: "2026-06-06T04:51:00.000Z",
    });

    await runDailyChangelogCron({
      now: new Date("2026-06-06T04:51:00.000Z"),
      store,
      summarizer: flakySummarizer,
    });
    expect(store.mergeGenerationJobs[0]).toMatchObject({
      status: "completed",
      attemptCount: 2,
      lastError: null,
    });
    expect(calls).toBe(2);
  });

  test("fences stale merge job attempts and deduplicates their entry writes", async () => {
    const store = InMemoryStore.seeded();
    await store.enqueueMergeGenerationJob({
      changelogId: "cl_acme",
      pullRequestNumber: 53,
      windowStartedAt: "2026-06-06T05:00:00.000Z",
      windowEndedAt: "2026-06-06T05:00:00.053Z",
    });
    const [firstClaim] = await store.claimMergeGenerationJobs({
      now: "2026-06-06T05:01:00.000Z",
      limit: 1,
    });
    store.mergeGenerationJobs[0]!.processingStartedAt =
      "2026-06-06T04:00:00.000Z";
    const [secondClaim] = await store.claimMergeGenerationJobs({
      now: "2026-06-06T06:02:00.000Z",
      limit: 1,
    });

    await store.retryMergeGenerationJob({
      jobId: firstClaim!.id,
      claimToken: firstClaim!.claimToken,
      error: "late first attempt",
      nextAttemptAt: "2026-06-06T06:07:00.000Z",
    });
    expect(store.mergeGenerationJobs[0]).toMatchObject({
      status: "processing",
      claimToken: secondClaim!.claimToken,
      attemptCount: 2,
    });

    const entryInput = {
      changelogId: "cl_acme",
      title: "One merge post",
      summary: "This post should only be persisted once.",
      category: "improvement" as const,
      status: "published" as const,
      publishedAt: "2026-06-06T05:00:00.000Z",
      windowEndedAt: "2026-06-06T05:00:00.053Z",
      sourcePullRequests: [
        { number: 53, url: "https://github.com/acme/app/pull/53" },
      ],
      generationKey: "merge:cl_acme:53",
    };
    const firstEntry = await store.createEntry(entryInput);
    const secondEntry = await store.createEntry(entryInput);
    expect(secondEntry.id).toBe(firstEntry.id);
    expect(
      store.entries.filter((entry) => entry.id === firstEntry.id),
    ).toHaveLength(1);

    await store.completeMergeGenerationJob({
      jobId: secondClaim!.id,
      claimToken: secondClaim!.claimToken,
    });
    expect(store.mergeGenerationJobs[0]).toMatchObject({
      status: "completed",
      claimToken: null,
    });
  });
});

describe("railway cron config", () => {
  test("runs the scheduler command on a native Railway cron schedule", () => {
    const config = JSON.parse(
      readFileSync(
        join(import.meta.dir, "../../../../railway.cron.json"),
        "utf8",
      ),
    );

    expect(config.deploy.startCommand).toBe("bun run railway:cron");
    expect(config.deploy.cronSchedule).toBe("*/15 * * * *");
    expect(config.deploy.healthcheckPath).toBeUndefined();
  });
});
